Code Quality
claraj/code_quality_issues pull request #10
Opened 2021-04-21 18:45 UTC by johnnyvuanly

2021-04-21 18:52 UTC, claraj commented
@GabrielGramlich can you review?

2021-04-21 19:20 UTC, GabrielGramlich commented on convert_state.py
> +    state_Abbr2 = {} # dictionary of state name keys and state abbreviation values
While you've made this snake case, the "Abbr" should still be all lowercase, and the state_abbr and state_abbr2 should be more distinct, perhaps abbreviations and states instead.

2021-04-21 19:21 UTC, GabrielGramlich commented on convert_state.py
> +        print ('The abbreviation for' +  user_input + ' is ' + result)
While I don't think the linter catches this, I'd recommend changing these to an f string, as there's more than one variable being added to the string.

2021-04-21 19:22 UTC, GabrielGramlich commented on convert_state.py
> +        print('Abreviation not found')
There's a typo in "Abreviation" here. Should be two b's.

2021-04-21 19:27 UTC, GabrielGramlich commented on convert_state.py
> +    for statekey, statevalue in state_Abbr.items() :
statekey, statevalue aren't really meaningful. Which is which?

2021-04-22 20:20 UTC, claraj requested changes
Looking much better, still some issues to fix

2021-04-22 20:20 UTC, claraj commented on convert_state.py
>      with open('data.json','r') as file:
put a space after the commas in arguments

2021-04-22 20:20 UTC, claraj commented on convert_state.py
> +    # print(data)
Remove this line

2021-04-22 20:20 UTC, claraj commented on convert_state.py
> +    state_abbr = data # dictionary of state abbreviations keys and state name values
Can you think of a better variable name?

2021-04-22 20:20 UTC, claraj commented on convert_state.py
> +    state_abbr2 = {} # dictionary of state name keys and state abbreviation values
Can you think of a better variable name?

2021-04-22 20:20 UTC, claraj commented on convert_state.py
> +        print('2. Convery abbreviation to state')
Fix spelling "Convert"

2021-04-22 20:20 UTC, claraj commented on convert_state.py
> +        elif choice==  '3':
Fix spacing around operators

2021-12-02 00:00 UTC, closed without merging