Fix code quality
claraj/code_quality_issues pull request #5
Opened 2021-04-21 18:31 UTC by ajgoranson

2021-04-21 18:33 UTC, claraj commented
@4LineTime can you review?

2021-04-21 18:44 UTC, 4LineTime commented
Looking good! I like the way you changed the menu function!

2021-04-21 19:13 UTC, 4LineTime commented
Beautiful!

2021-04-22 20:41 UTC, claraj requested changes
Looking much better! A few things to look at and fix please.

2021-04-22 20:41 UTC, claraj commented on convert_state.py
> +    """ Main method """
This is a function.   Describe what it does

2021-04-22 20:41 UTC, claraj commented on convert_state.py
> +    state_name_keys = json_data # dictionary of state abbreviations keys and state name values
Use a more specific variable name like states_abbreviations_to_names and then it's more obvious which dictionary is which, and you don't need the comment

2021-04-22 20:41 UTC, claraj commented on convert_state.py
> +    state_dictionary = {} # dictionary of state name keys and state abbreviation values
Use a more specific variable name like state_names_to_abbreviations and then it's more obvious which dictionary is which, and you don't need the comment

2021-04-22 20:41 UTC, claraj commented on convert_state.py
> +    Takes states and converts to abbreviation
More specifically, it asks the user for a state

2021-04-22 20:41 UTC, claraj commented on convert_state.py
> +    Take state abbreviation to a state
Be more specific

2021-12-02 00:00 UTC, closed without merging