Code quality issues
claraj/code_quality_issues pull request #6
Opened 2021-04-21 18:32 UTC by 4LineTime

Modified style, spelling and grammar issues in convert_state.py

2021-04-21 18:33 UTC, claraj commented
@ajgoranson can you review?

2021-04-21 19:14 UTC, ajgoranson commented
Dang This looks good! I would like your use of variable names

2021-04-22 20:37 UTC, claraj requested changes
Looks much better! A few small issues to look at.

2021-04-22 20:37 UTC, claraj commented on convert_state.py
> +        elif choice ==  '3':
Single space after ==

2021-04-22 20:37 UTC, claraj commented on convert_state.py
> +    user_input = input('Enter state name ').capitalize()   # User inputs state name
This comment isn't needed

2021-05-03 19:43 UTC, claraj commented on convert_state.py
> +        print('The abbreviation for ' +  user_input + ' is ' + result)
use f-string

2021-05-03 19:43 UTC, claraj reviewed
couple of small comments but looks much better. thanks!

2021-12-02 00:00 UTC, closed without merging