Spelling fixed
claraj/code_quality_issues pull request #7
Opened 2021-04-21 18:33 UTC by PickleEric

2021-04-21 18:45 UTC, claraj commented
@svenJonis138 can you review?

2021-04-21 19:34 UTC, svenJonis138 commented
Just got finished with mine, glad you got it working!
SJ

2021-04-22 20:23 UTC, claraj requested changes
Looking much better! Few things to take a look at.

2021-04-22 20:23 UTC, claraj commented on convert_state.py
>      with open('data.json','r') as file:
Space after comma in arguments

2021-04-22 20:23 UTC, claraj commented on convert_state.py
> +        print("2. Convert abbreviation to state")
Use single quotes

2021-04-22 20:23 UTC, claraj commented on convert_state.py
>          if choice=="1":
Single quotes for all strings, put a space before and after the == operator `if choice == '1':`

2021-04-22 20:23 UTC, claraj commented on convert_state.py
> +        print('State Not found')
Be consistent with capitalization

2021-04-22 20:23 UTC, claraj commented on convert_state.py
> +        print ( "The abbreviation for " + user_input + " is " + result + ".")
recommend f-string

2021-04-22 20:23 UTC, claraj commented on convert_state.py
> +        print("The state with the abbreviation." + user_input + " is " + result)
recommend f-string

2021-12-02 00:00 UTC, closed without merging